# Important for debugging and testing
epochs: 100
num_workers: 8
batch_size: 16

test_mode: 1         # 1:true   0:False

weak_ratio: 0.1      # ratio of weakly-supervised

min_val: 0
val_freq: 1
val_batch_size: 1
seed: 815

# weak-supervised cfgs
pretraining: True
model_path: /home/ybc/桌面/UCL/Result/S3DIS/0.1/base/best.pth

# dataset
num_classes: 13
feature_keys: x,heights

dataset:
  common:
    NAME: S3DIS
    data_root: /home/ybc/桌面/Dataset/
    test_area: 5
    voxel_size: 0.04
  train:
    split: train
    voxel_max: 8000
    loop: 30
    presample: True
    variable: False
    shuffle: True
  val:
    split: val
    voxel_max: null
    presample: True
    loop: 1
    variable: False
    shuffle: True
  test:
    split: test
    voxel_max: null
    presample: False

# data augmentation
datatransforms:
  train: [ChromaticAutoContrast, PointsToTensor, PointCloudScaling, PointCloudXYZAlign, PointCloudRotation, PointCloudJitter, ChromaticDropGPU, ChromaticNormalize]
  val: [PointsToTensor, PointCloudXYZAlign, ChromaticNormalize]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0, 0, 1]
    jitter_sigma: 0.005
    jitter_clip: 0.02


# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
layer_decay: 0 # no layer decay by default
step_per_update: 1
start_epoch: 1
sched_on_epoch: True

ignore_index: null

cls_weighed_loss: False

criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.2

optimizer:
  NAME: 'adamw'  # performs 1 point better than adam
  weight_decay: 1.0e-4

# lr_scheduler:
sched: cosine
warmup_epochs: 0

min_lr: 1.0e-5 #
lr: 0.01 # LR linear rule.

grad_norm_clip: 10


# ---------------------------------------------------------------------------- #
# Model Information
# ---------------------------------------------------------------------------- #
model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointMetaBaseEncoder   # PointNextEncoder  PointMetaBaseEncoder
    blocks: [1, 3, 5, 3, 3]
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1
    sa_use_res: False
    width: 32
    in_channels: 4
    expansion: 1  # 4
    radius: 0.1
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'   # ballquery
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: PointNextDecoder
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: null
    norm_args:
      norm: 'bn'
